### PR TITLE
Fixes #2 

### LINKED ISSUE #2: Remove 'cd'
Remove all usages of `cd ` from Workflow.m.
It does not work in compiled code.
@incei FYI

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

File: Evaluation/Workflow.m [hunk 1]
```diff
@@ -6,62 +6,68 @@
...
 % alternative #1: ReportOutput_path must be empty. If not, report generation will fail
 status = system([MarkdownJoiner_path ' -i ' REOutput_path ' -o ' ReportOutput_path]);
 
 % alternative #2: (CAUTION) ReportOutput_path will be cleared first
 %status = system([MarkdownJoiner_path ' -i ' REOutput_path ' -o ' ReportOutput_path ' -f']);
 
-if status~=0
-    error('MarkdownJoiner failed');
-end
+if status~=0 error('MarkdownJoiner failed'); end
```
Comment (Yuri05) [inline Evaluation/Workflow.m:72]: Must write the if-statement in one line in order to let **compiled version** of RE work

**Review by Incei — COMMENTED** [review]
all good, and agreed with the changes
